name: frent
description: "A new Flutter project."

publish_to: "none" # Supprimer cette ligne si vous souhaitez publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0" # Assurez-vous que votre version Dart est compatible

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0 # Mise à jour vers la dernière version disponible
  shared_preferences: ^2.2.2 # Mise à jour vers la dernière version disponible
  provider: ^6.1.2 # Gestion d'état avec Provider
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.6
  mongo_dart: ^0.10.4
  google_fonts: ^6.1.0

  open_file: ^3.5.10
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Outils de linting pour maintenir un code propre

flutter:
  uses-material-design: true
  assets:
    - images/logo.png # Correction du chemin d'accès aux assets
